login/urls.py
from django.urls import path
from .views import login, registrasi, selrole

app_name = 'login'

urlpatterns = [
    path('selectrole/', selrole, name = 'selrole'),
    path('registrasi/', registrasi, name = 'registrasi'),
    path('login/', login, name ='login')
]

main_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('station/', include('station.urls', namespace='station')),
    path('sepeda/', include('sepeda.urls', namespace='sepeda')),
    path('event/', include('event.urls', namespace='event')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('login/', include('login.urls', namespace='login')),
    path('topup/', include('topup.urls', namespace='topup')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('laporan/', include('laporan.urls', namespace='laporan'))
]

login/models.py
from django.db import models

class Profile(models.Model):
    nomor_ktp = models.CharField(max_length=300)
    nama_lengkap = models.CharField(max_length=300)
    tanggal_lahir = models.DateField()
    email = models.EmailField()
    nomor_tlp = models.CharField(max_length=300)
    alamat = models.CharField(max_length=300)

class User(models.Model):
    nomor_ktp = models.CharField(max_length=300)
    email = models.EmailField()

class Person(models.Model):
    ktp = models.CharField(max_length=300)
    nama = models.CharField(max_length=300)
    tgl_lahir = models.DateField()
    email = models.EmailField()
    no_telp = models.CharField(max_length=300)
    alamat = models.CharField(max_length=300)

    class Meta:
        managed = False
        db_table = 'person'

class Anggota(models.Model):
    no_kartu = models.CharField(max_length=300)
    saldo = models.IntegerField()
    points = models.IntegerField()
    ktp = models.CharField(max_length=300)

    class Meta:
        managed = False
        db_table = 'anggota'

class Petugas(models.Model):
    ktp = models.CharField(max_length=300)
    gaji = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'petugas'

class Penugasan(models.Model):
    ktp = models.CharField(max_length=300)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    id_stasiun = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'penugasan'

class Laporan(models.Model):
    id_laporan = models.IntegerField()
    no_kartu_anggota = models.IntegerField()
    datetime_pinjam = models.DateTimeField()
    nomor_sepeda = models.IntegerField()
    id_stasiun = models.IntegerField()
    status = models.CharField(max_length=300)

    class Meta:
        managed = False
        db_table = 'laporan'

class Transaksi(models.Model):
    no_kartu_anggota = models.IntegerField()
    date_time = models.DateTimeField()
    jenis = models.CharField(max_length=300)
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'transaksi'

class Role(models.Model):
    role = models.CharField(max_length=7)

login/forms.py
from django import forms
# from datetime import datetime
from .models import Profile,User,Role

# year_range = 100
# current_year = datetime.now().year

class RegistrasiForm(forms.ModelForm):
    nomor_ktp = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Identity Card Number',
        }
    ))
    nama_lengkap = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Full Name',
        }
    ))
    tanggal_lahir = forms.DateField(widget=forms.DateInput(
        attrs={
            'type': 'text',
            'onfocus': '(this.type="date")',
            'onblur': '(this.type="text")',
            'class': 'form-control',
            'placeholder': 'Birthday',
        }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'type': 'email',
            'class': 'form-control',
            'placeholder': 'E-mail',
        }
    ))
    nomor_tlp = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Phone Number',
        }
    ))
    alamat = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Address',
        }
    ))

    class Meta:
        model = Profile
        fields = ('nomor_ktp', 'nama_lengkap', 'tanggal_lahir', 'email', 'nomor_tlp', 'alamat')

class LoginForm(forms.ModelForm):
    nomor_ktp = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Identity Card Number',
        }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'type': 'email',
            'class': 'form-control',
            'placeholder': 'E-mail',
        }
    ))

    class Meta:
        model = User
        fields = ('nomor_ktp', 'email',)

class RoleForm(forms.ModelForm):
    ROLE_CHOICES = (
        ('Anggota', 'Anggota'),
        ('Petugas', 'Petugas'),
        ('Admin', 'Admin')
    )
    role = forms.ChoiceField(choices=ROLE_CHOICES)

    class Meta:
        model = Role
        fields = ('role',)

login/views.py
# import os

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection
from .models import User,Profile,Person,Anggota,Petugas,Penugasan,Role
from .forms import RegistrasiForm, LoginForm, RoleForm


def selrole(request):
    form = RoleForm()
    if request.method == 'POST':
        if form.is_valid():
            result = form.cleaned_data.get('role')
            if result == 'Anggota':
                request.session['role'] = 'anggota'
            if result == 'Admin':
                request.session['role'] = 'admin'
            else:
                request.session['role'] = 'petugas'
        return HttpResponseRedirect(reverse('registrasi'))
    return render(request, 'login/select_role.html', {'form':form})

def registrasi(request):
    form = RegistrasiForm()
    if request.method == 'POST':
        if form.is_valid():
            result = [form.cleaned_data.get('nomor_ktp'), form.cleaned_data.get('nama_lengkap'),
                  form.cleaned_data.get('tanggal_lahir'), form.cleaned_data.get('email'),
                  form.cleaned_data.get('nomor_tlp'), form.cleaned_data.get('alamat')]
            request.session['no_ktp'] == form.cleaned_data.get('nomor_ktp')
            if request.session['role'] == 'anggota':
                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO PERSON values(%s, %s, %s, %s, %s, %s)", result)
                    cursor.execute("INSERT INTO ANGGOTA values(%s, 0, 0, %s)", [form.cleaned_data.get('nomor_ktp'), ])
                return HttpResponseRedirect(reverse('login'))
            if request.session['role'] == 'petugas':
                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO PERSON values(%s, %s, %s, %s, %s, %s)", result)
                    cursor.execute("INSERT INTO PETUGAS values(%s, 30000)", [form.cleaned_data.get('nomor_ktp'), ])
                return HttpResponseRedirect(reverse('login'))
            if request.session['role'] == 'admin':
                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO PERSON values(%s, %s, %s, %s, %s, %s)", result)
                    cursor.execute("INSERT INTO PETUGAS values(%s, 0)", [form.cleaned_data.get('nomor_ktp'), ])
                return HttpResponseRedirect(reverse('login'))
    return render(request, 'login/register.html', {'form':form})

def login(request):
    form = LoginForm()
    if request.method == 'POST':
        if form.is_valid():
            input = [form.cleaned_data.get('nomor_ktp'), form.cleaned_data.get('email')]
            request.session['no_ktp'] = result[0]
            user = Person.objects.raw('SELECT * FROM PERSON WHERE no_ktp = %s AND email = %s', input)
            if list(user):
                request.session['no_ktp'] = input[0]
                if list(Anggota.objects.raw('SELECT * FROM ANGGOTA WHERE no_ktp = %s', input[0])):
                    request.session['role'] = 'anggota'
                if list(Petugas.objects.raw('SELECT * FROM PETUGAS WHERE no_ktp = %s AND gaji = 0', input[0])):
                    request.session['role'] = 'admin'
                else:
                    request.session['role'] = 'petugas'
            return HttpResponseRedirect(reverse('homepage'))
    return render(request, 'login/login.html', {'form':form})

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('homepage'))

# Create your views here.

login/templates/login/login.html
{% extends 'base.html' %}
{% load static %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container outerblock">
        <div class="twbs">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card bg-dimgray">
                            <div class="card-header">
                                <h2 class="text-center text-palegreen">Login</h2>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'login:login' %}" method="POST">
                                    <!-- {% if errors %}
                                    <h5 class="text-white"><strong>{{ errors }}</strong></h5>
                                    {% endif %} -->
                                    {% csrf_token %}
                                    <div class="form-group text-white">
                                        {{ form.nomor_ktp }}
                                        <!-- <label for="{{ auth_form.username.id_for_label }}">Alamat Email</label>
                                        <input type="email" class="form-control form-input-registration" name="{{ auth_form.username.html_name }}" id="{{ auth_form.username.id_for_label }}" placeholder="Masukkan email anda"> -->
                                    </div>
                                    <div class="form-group text-white">
                                        {{ form.email }}
                                        <!-- <label for="{{ auth_form.password.id_for_label }}">Password</label>
                                        <input type="password" class="form-control form-input-registration" name="{{ auth_form.password.html_name }}" id="{{ auth_form.password.id_for_label }}" placeholder="Masukkan password anda"> -->
                                    </div>
                                    <button type="submit" class="btn btn-block bg-palegreen hover-darkergreen">Login</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

login/templates/login/register.html
{% extends "base.html" %}
{% load static %}

{% block additional_styles %}
	<link rel="stylesheet" href="{% static 'login/css/style.css' %}">
{% endblock %}

{% block content %}
	<div class="center">
		<div class="twbs">
			<div class="container">
				<div class="row">
					<div class="text-palegreen">
						<h1 class="">Formulir Registrasi</h1>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="card bg-dimgray">
						<div class="card-header text-palegreen">
								<h2>Registrasi Akun Baru</h2>
							</div>
						<div class="card-body">
							<form action="{% url 'login:registrasi' %}" method="POST">
								<div class="form-group text-white">
									{% csrf_token %}
									{{ form.as_p }}
								</div>
								<button type="submit" class="save btn btn-block bg-palegreen hover-darkergreen">Daftar</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

login/templates/login/select_role.html
{% extends 'base.html' %}
{% load static %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container outerblock">
        <div class="twbs">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card bg-dimgray">
                            <div class="card-header">
                                <h2 class="text-center text-palegreen">Select role</h2>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'login:login' %}" method="POST">
                                    <!-- {% if errors %}
                                    <h5 class="text-white"><strong>{{ errors }}</strong></h5>
                                    {% endif %} -->
                                    {% csrf_token %}
                                    <div class="form-group text-white">
                                        {{ form.role }}
                                        <!-- <label for="{{ auth_form.username.id_for_label }}">Alamat Email</label>
                                        <input type="email" class="form-control form-input-registration" name="{{ auth_form.username.html_name }}" id="{{ auth_form.username.id_for_label }}" placeholder="Masukkan email anda"> -->
                                    </div>
                                    <button type="submit" class="btn btn-block bg-palegreen hover-darkergreen">Select</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}