main_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('station/', include('station.urls', namespace='station')),
    path('sepeda/', include('sepeda.urls', namespace='sepeda')),
    path('event/', include('event.urls', namespace='event')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('login/', include('login.urls', namespace='login')),
    path('topup/', include('topup.urls', namespace='topup')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('laporan/', include('laporan.urls', namespace='laporan'))
]

sepeda/urls.py
from django.urls import path
from .views import sepeda, create_sepeda, sepeda_table, create, update, update_sepeda

app_name = 'sepeda'

urlpatterns = [
    path('', sepeda, name='sepeda'),
    path('create', create, name='create'),
    path('create_sepeda', create_sepeda, name='create_sepeda'),
    path('table', sepeda_table, name='table'),
    path('update', update, name='update'),
    path('update_sepeda', update_sepeda, name='update_sepeda'),
]

sepeda/models.py
from django.db import models

# Create your models here.

class Sepeda(models.Model):
    nomor = models.AutoField(primary_key=True)
    merk = models.CharField(max_length=10)
    jenis = models.CharField(max_length=50)
    status = models.BooleanField()
    id_stasiun = models.CharField(max_length=10)
    no_kartu_penyumbang = models.CharField(max_length=20)

sepeda/forms.py
from django import forms
from django.db import connection

STATUS_CHOICES=[
    ('tersedia', 'Tersedia'),
    ('tidak_tersedia', 'Tidak Tersedia'),
]

class CreateForm(forms.Form):
    error_messages = {
        'required': 'Please fill in the input',
    }

    merk = forms.CharField(label='Merk', max_length=10, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    jenis = forms.CharField(label='Jenis', max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    status = forms.CharField(label='Status', widget=forms.Select(attrs={'class': 'form-control'}, choices=STATUS_CHOICES), required=True)
    stasiun = forms.CharField(label='Station', widget=forms.Select(attrs={'class': 'form-control'}, choices=STATUS_CHOICES), required=False)
    penyumbang = forms.CharField(label='Donator', widget=forms.Select(attrs={'class': 'form-control'}, choices=STATUS_CHOICES), required=False)

class UpdateForm(forms.Form):
    error_messages = {
        'required': 'Please fill in the input',
    }

    lat = forms.IntegerField(label='Latitude', required=False)
    lon = forms.IntegerField(label='Longitude', required=False)

sepeda/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CreateForm, UpdateForm
from .models import Sepeda

response = {}

def sepeda(request):
    message = Sepeda.objects.all()
    response['sepeda_list'] = message
    html = 'sepeda/sepeda.html'
    return render(request, html, response)

def create(request):
    html = 'sepeda/create.html'
    response['createform'] = CreateForm
    return render(request, html, response)

def create_sepeda(request):
    form = CreateForm(request.POST)
    if(request.method == 'POST' and form.is_valid()):
        prev_nomor = Sepeda.objects.raw("Select nomor from sepeda order by station_id DESC limit 1")
        nomor = int(prev_nomor[0].nomor) + 1
        merk = form.cleaned_data['merk']
        jenis = form.cleaned_data['jenis']
        status = form.cleaned_data['status']
        id_stasiun = form.cleaned_data['id_stasiun']
        no_kartu_penyumbang = form.cleaned_data['no_kartu_penyumbang']
        with connection.cursor() as cursor:
            cursor.execute("insert into sepeda values(%s, %s, %s, %s, %s, %s)", [nomor, merk, jenis, status, id_stasiun, no_kartu_penyumbang])
        return HttpResponseRedirect('/sepeda/table')
    else:
        return HttpResponseRedirect('/sepeda/table')

def sepeda_table(request):
    message = Sepeda.objects.all()
    response['sepeda_list'] = message
    html = 'sepeda/sepeda.html'
    return render(request, html , response)

def update(request):
    html = 'sepeda/update.html'
    response['updateform'] = UpdateForm
    return render(request, html, response)

def update_sepeda(request, station_id):
    sepeda = Sepeda.objects.raw('Select * from sepeda where nomor = %s', [nomor])
    initial_sepeda = {
        'nomor': sepeda[0].nomor,
        'merk': sepeda[0].merk,
        'jenis': sepeda[0].jenis,
        'status': sepeda[0].status,
        'id_stasiun': sepeda[0].id_stasiun,
        'no_kartu_penyumbang': sepeda[0].no_kartu_penyumbang
    }

    form = UpdateForm(request.POST)
    if(request.method == 'POST' and form.is_valid()):
        if form.has_changed():
            for c in form.changed_data:
                data = [form.cleaned_data.get(c), form.cleaned_data.get('station_id')]
                with connection.cursor() as cursor:
                    cursor.execute('UPDATE sepeda set %s = %s WHERE nomor = %s' %(c, '%s', '%s'), data)
        return HttpResponseRedirect('/sepeda/table')
    else:
        return HttpResponseRedirect('/sepeda/table')

sepeda/templates/sepeda/create.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'static/sepeda/css/sepeda.css' %}">
    <title>Cyclink Bikes</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<main>
    <div class="container my-3">
        <form method="POST">
            {% csrf_token %}
            {% for field in createform %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <br>
            <button type="submit" class="btn btn-info mb-2 mr-3 float-left">Create</button>
        </form>
    </div>
</main>
<div class="z"></div>
{% endblock %}

sepeda/templates/sepeda/sepeda.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'static/sepeda/css/sepeda.css' %}">
    <title>Cyclink Bikes</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<main>
    <div class="container">
        <table class="table table-hover table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Merk</th>
                    <th>Jenis</th>
                    <th>Status</th>
                    <th>Stasiun</th>
                    <th>Penyumbang</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for station in station_list %}
                <tr>
                    <td>{{sepeda.merk}}</td>
                    <td>{{sepeda.jenis}}</td>
                    <td>{{sepeda.status}}</td>
                    <td>{{sepeda.stasiun}}</td>
                    <td>{{sepeda.penyumbang}}</td>
                    <td><button class="btn btn-info mb-2 mr-3 float">Update</button>
                        <button class="btn btn-danger mb-2 mr-3 float">Delete</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'sepeda:create' %}" class="btn btn-info mb-2 mr-3 float-left">Create</a>
    </div>
</main>
<div class="z"></div>
{% endblock %}