main_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('station/', include('station.urls', namespace='station')),
    path('sepeda/', include('sepeda.urls', namespace='sepeda')),
    path('event/', include('event.urls', namespace='event')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('login/', include('login.urls', namespace='login')),
    path('topup/', include('topup.urls', namespace='topup')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('laporan/', include('laporan.urls', namespace='laporan'))
]

station/urls.py
from django.urls import path
from .views import station, create_station, station_table, create, update, update_station

app_name = 'station'

urlpatterns = [
    path('', station, name='station'),
    path('create', create, name='create'),
    path('create_station', create_station, name='create_station'),
    path('table', station_table, name='table'),
    path('update', update, name='update'),
    path('update_station', update_station, name='update_station')
]

station/models.py
from django.db import models

# Create your models here.

class StationStation(models.Model):
    address = models.TextField()
    lat = models.IntegerField()
    lon = models.IntegerField()
    name = models.CharField(max_length=50)
    station_id = models.IntegerField(primary_key=True)

    class Meta:
        db_table = 'station_station'

station/forms.py
from django import forms

class CreateForm(forms.Form):
    error_messages = {
        'required': 'Please fill in the input',
    }

    name = forms.CharField(label='Name', max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label='Address', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lat = forms.IntegerField(label='Latitude', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    lon = forms.IntegerField(label='Longitude', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))

class UpdateForm(forms.Form):
    error_messages = {
        'required': 'Please fill in the input',
    }

    lat = forms.IntegerField(label='Latitude', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    lon = forms.IntegerField(label='Longitude', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))

station/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection
from .forms import CreateForm, UpdateForm
from .models import StationStation

response = {}

def station(request):
    message = StationStation.objects.all()
    response['station_list'] = message
    html = 'station/station.html'
    return render(request, html, response)

def create(request):
    html = 'station/create.html'
    response['createform'] = CreateForm
    return render(request, html, response)

def create_station(request):
    form = CreateForm(request.POST)
    if(request.method == 'POST' and form.is_valid()):
        prev_station_id = StationStation.objects.raw("Select station_id from station order by station_id DESC limit 1")
        station_id = int(prev_station_id[0].station_id) + 1
        address = form.cleaned_data['address']
        lat = form.cleaned_data['lat']
        lon = form.cleaned_data['lon']
        name = form.cleaned_data['name']
        
        with connection.cursor() as cursor:
            cursor.execute("insert into station values(%s, %s, %s, %s)", [station_id, name, address, lat, lon])
        return HttpResponseRedirect('/station/table')
    else:
        return HttpResponseRedirect('/station/table')

def station_table(request):
    message = StationStation.objects.all()
    response['station_list'] = message
    html = 'station/station.html'
    print(response)
    return render(request, html , response)

def update(request):
    html = 'station/update.html'
    response['updateform'] = UpdateForm
    return render(request, html, response)

def update_station(request, station_id):
    station = StationStation.objects.raw('Select * from station where station_id = %s', [station_id])
    initial_station = {
        'station_id': station[0].station_id,
        'name': station[0].name,
        'address': station[0].address,
        'lat': station[0].lat,
        'lon': station[0].lon
    }

    form = UpdateForm(request.POST)
    if(request.method == 'POST' and form.is_valid()):
        if form.has_changed():
            for c in form.changed_data:
                data = [form.cleaned_data.get(c), form.cleaned_data.get('station_id')]
                with connection.cursor() as cursor:
                    cursor.execute('UPDATE station set %s = %s WHERE station_id = %s' %(c, '%s', '%s'), data)
        return HttpResponseRedirect('/station/table')
    else:
        return HttpResponseRedirect('/station/table')

station/templates/station/create.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'station/css/station.css' %}">
    <title>Cyclink Stations</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<main>
    <div class="container my-3">
        <form method="POST">
            {% csrf_token %}
            {% for field in createform %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <br>
            <button type="submit" class="btn btn-info mb-2 mr-3 float-left">Create</button>
        </form>
    </div>
</main>
<div class="z"></div>
{% endblock %}

station/templates/station/station.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'station/css/station.css' %}">
    <title>Cyclink Stations</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<main>
    <div class="container">
        <table class="table table-hover table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Station ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for b in station_list %}
                <tr>
                    <td>{{ b.station_id }}</td>
                    <td>{{ b.name }}</td>
                    <td>{{ b.address }}</td>
                    <td>{{ b.lon }}</td>
                    <td>{{ b.lat }}</td>
                    <td><a href="{% url 'station:update_station' station_id=b.station_id %}"><button class="btn btn-info mb-1 mr-1">Update</button></a>
                    <button class="btn btn-danger mb-1 mr-1">Delete</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'station:create' %}" class="btn btn-info mb-2 mr-3 float-left">Create</a>
    </div>
</main>
<div class="z"></div>


{% endblock %}

station/templates/station/update.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'station/css/station.css' %}">
    <title>Cyclink Stations</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<main>
    <div class="container my-3">
        <form method="POST">
            {% csrf_token %}
            {% for field in updateform %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <br>
            <button type="submit" class="btn btn-info mb-2 mr-3 float-left">Update</button>
        </form>
    </div>
</main>
<div class="z"></div>
{% endblock %}